name: Movecraft-Towny
version: ${project.version}
main: net.tylers1066.movecrafttowny.movecrafttowny.MovecraftTowny
api-version: 1.13
depend: [Movecraft, Towny]
authors: [TylerS1066, BaccaYarro, cccm5]
description: Movecraft and Towny Integration
