name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Movecraft-Towny
      uses: actions/checkout@v2
      with:
        path: Movecraft-Towny
    - name: Checkout Movecraft
      uses: actions/checkout@v2
      with:
        repository: 'TylerS1066/Movecraft'
        path: Movecraft
        ref: 'towny'
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      id: cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    # Run Spigot BuildTools for NMS if required
    - name: Setup BuildTools
      if: steps.cache.outputs.cache-hit != 'true'
      run: mkdir BuildTools
    - name: Download BuildTools
      if: steps.cache.outputs.cache-hit != 'true'
      run: wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    - name: 1.10.2
      if: steps.cache.outputs.cache-hit != 'true'
      run: cd BuildTools && java -jar BuildTools.jar --rev 1.10.2
    - name: 1.11.2
      if: steps.cache.outputs.cache-hit != 'true'
      run: cd BuildTools && java -jar BuildTools.jar --rev 1.11.2
    - name: 1.12.1
      if: steps.cache.outputs.cache-hit != 'true'
      run: cd BuildTools && java -jar BuildTools.jar --rev 1.12.1
    
    # Build Movecraft
    - name: Build Movecraft
      run:  mvn -B package -T 1C --file Movecraft/pom.xml

    # Build Movecraft-Towny
    - name: Build Movecraft-Towny
      run: mvn -B package -T 1C --file Movecraft-Towny/pom.xml

    - name: Stage jar
      run: mkdir staging && cp Movecraft-Towny/target/Movecraft-Towny*.jar staging
    - name: Rename jar
      run: mv staging/Movecraft-Towny*.jar staging/Movecraft-Towny_$GITHUB_SHA.jar
    - name: Upload jar
      uses: actions/upload-artifact@v2
      with:
        name: Movecraft-Towny_Dev-Build
        path: staging/Movecraft-Towny_*.jar
