name: Java CI

on: [workflow_dispatch, push, pull_request]

jobs:
  # Build Movecraft-Towny
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Movecraft-Towny
      uses: actions/checkout@v2
      with:
        path: Movecraft-Towny
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt-hotspot'
        java-version: '16'
    - name: Cache Maven packages
      id: cacheMain
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2

    # Build Movecraft-Towny
    - name: Build Movecraft-Towny
      run: mvn -B package -T 1C --file Movecraft-Towny/pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Stage jar
      run: mkdir staging && cp Movecraft-Towny/target/Movecraft-Towny*.jar staging
    - name: Rename jar
      run: mv staging/Movecraft-Towny*.jar staging/Movecraft-Towny_$GITHUB_SHA.jar
    - name: Upload jar
      uses: actions/upload-artifact@v2
      with:
        name: Movecraft-Towny_Dev-Build
        path: staging/Movecraft-Towny_*.jar
